<a href="https://colab.research.google.com/github/obedest/DeepLearning-with-PyTorch---Codemy.com/blob/main/DeepLearning_with_PyTorch_Codemy_com.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import torch
import numpy as np

In [6]:
# lists
my_list = [[1, 2, 3, 4], [1, 2, 3, 4]]
my_list

[[1, 2, 3, 4], [1, 2, 3, 4]]

In [8]:
# numpy arrays
np1 = np.random.rand(2, 4)
np1

array([[0.43905139, 0.58317886, 0.50823081, 0.13542961],
       [0.9303773 , 0.49377578, 0.08886755, 0.71445421]])

In [9]:
# tensors
tensor_2d = torch.rand(2, 4)
tensor_2d

tensor([[0.4012, 0.1564, 0.5945, 0.2099],
        [0.8103, 0.1524, 0.1716, 0.4836]])

In [10]:
tensor_3d = torch.zeros(2, 3, 4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [16]:
# create tensor from numpy array
np_tensor = torch.tensor(np1)
np_tensor
# create tensor from list -- mine
list_tensor = torch.tensor(my_list)
list_tensor

tensor([[1, 2, 3, 4],
        [1, 2, 3, 4]])