<a href="https://colab.research.google.com/github/obedest/DeepLearning-with-PyTorch---Codemy.com/blob/main/DeepLearning_with_PyTorch_Codemy_com.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [198]:
import torch
import numpy as np

In [199]:
# lists
my_list = [[1, 2, 3, 4], [1, 2, 3, 4]]
my_list

[[1, 2, 3, 4], [1, 2, 3, 4]]

In [200]:
# numpy arrays
np1 = np.random.rand(2, 4)
np1

array([[0.16281021, 0.89292749, 0.65917241, 0.99695923],
       [0.04256427, 0.18968883, 0.01397625, 0.8468711 ]])

In [201]:
# tensors
tensor_2d = torch.rand(2, 4)
tensor_2d

tensor([[0.8379, 0.7600, 0.5392, 0.7351],
        [0.3014, 0.2400, 0.0066, 0.1641]])

In [202]:
tensor_3d = torch.zeros(2, 3, 4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [203]:
# create tensor from numpy array
np_tensor = torch.tensor(np1)
np_tensor
# create tensor from list -- mine
list_tensor = torch.tensor(my_list)
list_tensor

tensor([[1, 2, 3, 4],
        [1, 2, 3, 4]])

##Reshaping and slicing tensors

In [204]:
my_tensor = torch.arange(10)
my_tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [205]:
# Reshape and view
my_tensor = my_tensor.reshape(2, 5)
my_tensor

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [206]:
my_torch = torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [207]:
# Reshape if we don't know the number of items
my_torch1 = my_torch.reshape(2, -1)
my_torch1

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [208]:
my_torch2 = my_torch.reshape(-1, 2)
my_torch2

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [209]:
my_torch3 = my_torch.view(2, -1)
my_torch3

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [210]:
my_torch3[0][1] = 55
print(my_torch3)
print(my_torch)

tensor([[ 0, 55,  2,  3,  4],
        [ 5,  6,  7,  8,  9]])
tensor([ 0, 55,  2,  3,  4,  5,  6,  7,  8,  9])


In [211]:
# Slices
my_torch4 = torch.arange(10)
my_torch4

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [212]:
my_torch4 = my_torch4.reshape(5, -1)
my_torch4

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [213]:
my_torch4[:,1] #get the 1-nth column
my_torch4[:,0] #get the 0-nth column

tensor([0, 2, 4, 6, 8])

In [214]:
# return column
my_torch4[:,1:] #get the 1-nth column preserving the structure

tensor([[1],
        [3],
        [5],
        [7],
        [9]])

##Tensor math operations

In [215]:
tensor_1 = torch.tensor([1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])
tensor_1

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [216]:
tensor_2 = torch.tensor([1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])
tensor_2

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [217]:
# addition
tensor_1 + tensor_2
torch.add(tensor_1, tensor_2)
tensor_1.add(tensor_2)

tensor([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

In [218]:
# subtraction
tensor_1 - tensor_2
torch.sub(tensor_1, tensor_2)

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [219]:
# multiplication
tensor_1 * tensor_2
torch.mul(tensor_1, tensor_2)

tensor([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144, 169, 196,
        225])

In [220]:
# division
tensor_1 / tensor_2
torch.div(tensor_1, tensor_2)

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [221]:
# remainder
tensor_1 % tensor_2
torch.remainder(tensor_1, tensor_2)

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [222]:
# exponents (powers)
torch.pow(tensor_1, tensor_2)

tensor([                 1,                  4,                 27,
                       256,               3125,              46656,
                    823543,           16777216,          387420489,
               10000000000,       285311670611,      8916100448256,
           302875106592253,  11112006825558016, 437893890380859375])

In [223]:
# reassignment
tensor_1 = tensor_1 + tensor_2
tensor_1
# OR USE UNDERSCORE _
tensor_1.add_(tensor_2)
tensor_1

tensor([ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45])